language: python
services:
  - docker
install:
  - make deps
script:
  - make test_cov
  - make lint
after_success:
  - make docker_build
deploy:
  provider: heroku
  app: salty-wave-26251
  api_key: ${HEROKU_API_KEY}
